### ISSUE TITLE
How to add an additional query parameter?

### ISSUE THREAD

**Issue by bluish5** [basti1302/traverson#39]
Hello, thanks for this good component!
I'm using it like this:

	traverson
		.from('rest/bookings/search')
		.newRequest()
		.follow('findByResource', 'bookings[$all]')
		.withTemplateParameters({
			resource : 6
		})
		.getResource(function(error, document) {
			if (error) {
				console.error('Bookings not found');
			} else {
				callback(document);
			}
		});

It works.
In my RESTful web service, built with Spring Data REST, I'm using "projections". In short, I can request a particular set of information on the resource I'm asking, specifying `projection=nameoftheprojection` as an additional query parameter.
At the end my URL will be:

    http://.../rest/bookings/search/findByResource?resource=6&projection=details

And then I have to follow `bookings` node, like I did in the code above.
How can I add such parameter using Traverson!
Kind regards

**Comment by basti1302** [comment]
`withRequestOptions` should do the trick.

Like this:
```
traverson
    .from('rest/bookings/search')
    .newRequest()
    .follow('findByResource', 'bookings[$all]')
    .withTemplateParameters({
        resource : 6
    })
    .withRequestOptions({
        qs: { projection: 'details' }
    })
    .getResource(function(error, document) {
        if (error) {
            console.error('Bookings not found');
        } else {
            callback(document);
        }
    });
```

Docs:

* https://github.com/basti1302/traverson/#headers-query-strings-http-basic-auth-oauth-and-whatnot
* https://github.com/basti1302/traverson/blob/master/api.markdown (see `withRequestOptions` section)
* https://github.com/request/request#requestoptions-callback

This should work well but actually an even  cleaner solution might be if your server side would include `projection` as an optional parameter in the URI template:

http://.../rest/bookings/search/findByResource?resource={resource}{&projection}

See https://tools.ietf.org/html/rfc6570#section-3.2.9

Benefit: Your API communicates to clients that this parameter can be used and it is no longer implicit knowledge, also you can omit `withRequestOptions` and just use `withTemplateParameters` with two values instead of one.

**Comment by xogeny** [comment]
I agree with @basti1302.  In my opinion, you are much better served by using a URI template.  This makes is very clear what query strings are allowed and which are not.  It also gets you farther from constructing your own URLs.

**Comment by bluish5** [comment]
Thank you @basti1302. withRequestOptions satisfies my need.
Thanks also for the suggestion of exposing projection parameter on the server side as any other template parameter, but it is not an option for me, as it is not how Spring Data REST projections work.

**Comment by basti1302** [comment]
Actually, looking at http://docs.spring.io/spring-data/rest/docs/2.3.0.RELEASE/reference/html/#projections-excerpts.projections the docs seem to suggest that using a `@Projection` annotation does indeed give you a URI template with an optional projections parameter `http://localhost:8080/persons/1{?projection}`.

I never used Spring Data REST, so maybe I barking up the wrong tree.

**Comment by bluish5** [comment]
You referred to invoking a resource using a projection (`http://localhost:8080/persons/1{?projection}` in your example), but in my case I'm invoking a search service built on the resource (`http://localhost:8080/persons/search/findByName?{name}`), using a projection on it (`projection=details`). 
In the description of such search service unfortunately `projection` parameter is not mentioned.
Maybe Spring Data REST is wrong here. If you agree I could open an issue on Spring Data REST.
