### ISSUE TITLE
Pass multiple values for the same template parameter

### ISSUE THREAD

**Issue by bluish5** [basti1302/traverson#41]
Hello, thank you for your good job!

I have following need today. I have a REST service with this search available:

    {
      "_links" : {
        "findByStatusIn" : {
          "href" : "http://localhost:8080/myapp/rest/myresources/search/findByStatusIn{?status}",
          "templated" : true
        }
      }
    }

`status` is a parameter that can be passed with multiple values, for instance:

    http://localhost:8080/myapp/rest/myresources/search/findByStatusIn?status=A&status=B&status=C

How can I pass multiple values for the same parameter using `withTemplateParameters`?

I tried this:

	.withTemplateParameters({
		status : ['A', 'B', 'C']
	})

but obtained

    http://localhost:8080/myapp/rest/myresources/search/findByStatusIn?status=A,B,C

Looking through Traverson code, `expand` function in `UrlTemplate.prototype.parse` seems not to support this.

**Comment by basti1302** [comment]
I'm not sure what to do here. I think the specific URI template fragment in your example (`{?status}`) does not allow for multiple values according to the [RFC6570](https://tools.ietf.org/html/rfc6570), does it?

If I read the RFC correctly, you would need the explode modifier `*`, combined with an expression type that expands named parameters (`;`, `?`, or `&`). See end of section 3.2.1. "Variable Expansion". For instance, something like `{&status*}` could do the trick.

Traverson uses [url-template](https://github.com/bramstein/url-template) (because the small file size makes it attractive when Traverson is used in the browser). The library claims "The implementation supports all levels defined in the specification and is extensively tested." Thus, I would expect that this works when the actual URI template is corrected on the server side. If not, I would suggest opening an issue at url-template.

Closing for now. Feel free to re-open, if you still think this is an issue with Traverson.re-open.

**Comment by bluish5** [comment]
Great note @basti1302!
I'll point it out to Spring Data REST.
