### ISSUE TITLE
Should POST response body be converted to JSON

### ISSUE THREAD

**Issue by jinder** [basti1302/traverson#44]
More of a question than a bug report at this stage, but should the response body of a POST be converted to an object if the content-type lists it as JSON?

At the moment, I'm doing this (angular + hal):

```
        return this.traversonFrom(dataSource._links.search.href)
            .follow()
            .post({query: searchTerm})
            .result.then(response => angular.fromJson(response.data));
```

**Comment by xogeny** [comment]
Why is your search using `POST` and not `GET`?  That seems very odd to me.  But ignoring that for the moment...

It really depends on the status code that the request returns.  There is some discussion of this issue [here](http://stackoverflow.com/questions/1226810/is-http-post-request-allowed-to-send-back-a-response-body).  Normally, a `POST` will return something like a `201` or `202`.  If it returns a `201`, it is supposed to return a `Location` header.

What is your "search" returning?  I would imagine it is a `200` (since it really seems to be conceptually just a `GET`).  In that case, then the body of the `POST` response could be marshaled up and returned as a promise.  But what if it returns a `201`?  As I mentioned above, it should return a `Location` header.  But, what if it **also** returns a body?

It would be good if the *type* of thing that was returned was consistent.  Let's consider these possible cases:

  1. Status: `200`, body
  2. Status: `201`, `Location`, no body
  3. Status: `201`, `Location`, body
  4. Status: `202`, no `Location`, no body

If we just look at the responses, we've got two cases (1 and 3) where there is a body (presumably JSON) and two where there isn't (2 and 4).  As I mentioned, it would be nice if the request returned the same type of thing in all cases.  But if we just returned the response body in all cases, that wouldn't be the case.  Furthermore, for case 2, we'd like to get the Location header information out somehow.

For cases 2, one thing that could be done (I have no idea how `traverson` handles this currently), you could actually add a `GET` request on the end, i.e., use the Location header and fetch that resource and return **that** response.

That leaves case 4 which is definitely problematic since you'll get nothing from that.  Perhaps `traverson` could simply return an empty body?

Of course, there are other possibilities as well (2xx responses) to deal with.

**Comment by basti1302** [comment]
The basic operations `get`, `post`, `put` and `delete` all return the full server response including the status code and the body as is, unprocessed. A special case is `getResources` which automatically transforms the JSON body to an object. At the moment, this automatic transform is only available for GET, though.

I agree that this is pretty inconvenient.

I suggest to make this configurable, so that you can enable JSON-to-object transformation for every operation. `getResource` would be a shortcut for enabling transformation and doing a `get`.

The default for `get`, `post`, `put` and `delete` would be to have the automatic transformation disabled, at least until the next major version version.

How does that sound, @jinder?

**Comment by jinder** [comment]
@xogeny - we're using a POST because we have quite a large and complicated search body that includes multiple search criteria, faceting and sorting.  We're using a 200 response, and our server will only ever return this (or an error code).

@basti1302 - yes that sounds good.  All our response bodies (if returned) will be JSON, so this would help to clean up our code.

**Comment by basti1302** [comment]
One addition, mainly from the discussion over at >https://github.com/basti1302/traverson-angular/issues/14>.

If automatic transformation from JSON to JS objects is enabled, one would probably also have different expecations for the handling of HTTP status codes of the last request of the traversal, namely, that all status codes outside the 2xx range call the callback with an error. (In contrast to the current behaviour, where 4xx and 5xx codes are not interpreted as an error).

Finally, #37 might be loosely related. If we decide on some breaking changes here, it would be a good time to also think about Content-Type headers once again.

**Comment by basti1302** [comment]
This has landed in release 2.1.0.

**Comment by Aracki** [comment]
I'm getting Status: 201 response after **post** method. But response i get is with no _body_ and no _header_ at all :-/

Screenshot above:

![github2](https://cloud.githubusercontent.com/assets/6129986/11839216/5cb963a0-a3ec-11e5-9ef6-cd8f654fd735.png)

**Comment by basti1302** [comment]
1. If you think this is a bug in traverson, it would probably be better to open a new ticket instead of appending a comment to an old, already closed ticket. 

2. Regarding your problem, could you check the network tab in dev tools? Is there a body in the response on for corresponding request? Are there headers shown for the response. 

If there is a response body and response headers coming from the server and Traverson somehow discards them, then this would be a bug in Traverson. I would need more info on how to reproduce this. If the server simply sends nothing, then I think Traverson works as designed here.
