### ISSUE TITLE
Feature? enable cache for follow to reduce number of requests?

### ISSUE THREAD

**Issue by joepjoosten** [basti1302/traverson#54]
I don't know if it's already in the package, but caching the url's to follow could help reduce the request made?

What's your opinion?

**Comment by dimik** [comment]
+1
I had to write my own cache solution (about 70 lines of code with ES2016 Decorators + Babel) to store 3rd param of "traverson.getResource" callback.

https://gist.github.com/dimik/bb656be267f91c1e9c63

**Comment by basti1302** [comment]
There's no caching in Traverson yet. I would really like to support proper caching or HTTP responses according to HTTP specs, but this is totally outside of the scope of Traverson, that is, I won't roll my own HTTP caching mechanism in Traverson. It would be ideal if the request library would support this (at least Traverson-on-the-server), but last time I looked it did not have support for caching. 

If someone has an idea how to add HTTP layer caching to Traverson, maybe by plugging some existing qualitiy HTTP caching library into Traverson, I'd welcome this.

The situation might be different for Traverson-on-the-client because we are ultimately using the Browser's AJAX mechanisms here, so caching should just work out of the box if your backend resources have the correct HTTP headers set.

@dimik I had only a very cursory look at your gist. What exactly does it do?

**Comment by dimik** [comment]
It stores 3rd param of your "getResource" methods callback for every followed link (step by step) based on link value and params.
When you call traverson.follow(['link1', 'link2', 'link3']).getResource(...)
cache will be looking roughly like this:

cache = {
  'link1': _traverson_context_for_link1_,
  'link1,link2':  _traverson_context_for_link1_and_link2,
  'link1,link2,link3':_traverson_context_for_link1_link2_link3,
}

So next time you call for example traverson.follow(['link1', 'link2', 'link5', 'link6']).getResource(...)
Actually it will be
cache['link1,link2'].continue().follow(['link5', 'link6'])

**Comment by basti1302** [comment]
But does this respect HTTP caching protocol headers? The response to the 'link1' and 'link2' resources could have changed in the mean time? How is the validity and the TTL of the cached responses controlled?

**Comment by dimik** [comment]
No it stores your Builder instance and not a server response.
That's all i need because if i do a search for example
i have to make 4 requests (3 for getting the search resource and 1 for search itself)
next i have to get next 100 results (resource from the same search _links object) so i use saved Builder instance to continue making request from step 3. 

You can also drop certain key if you want to re-request any data again

**Comment by basti1302** [comment]
@dimik This is a rather special use case. I will not implement caching builder instances in Traverson. If at all, than caching should happen on the HTTP layer, according to the specs that govern HTTP client side caching.

**Comment by basti1302** [comment]
Closing this for now as it mostly discusses a special case of caching and did not have any new input in months.

**Comment by xogeny** [comment]
Just a comment.  I agree with @basti1302's comment about respecting HTTP headers.  If the responses to `traverson`'s requests include the proper headers, the browser will cache them.  As such, the number of real requests over the wire will be reduced.  All this happens automatically in any browser.  So I'm not sure what you want to add here?  Anything that simply memoizes things (without regard to the actual response headers) is not correct, in my opinion.

**Comment by basti1302** [comment]
What @xogeny says is true for the case where Traverson is used in the browser. There, the situation is actually fine because browsers take care of the HTTP caching. However, when Traverson is used in Node.js there is nothing that takes care of the caching for us. That's why I said it would be nice if the request library would take care of this. Naturally, proper caching according to the HTTP spec is also beneficial for HTTP clients in a Node.js context, doing server to server communication, or whatever.

**Comment by ramirez** [comment]
This could be a feasible candidate for a wrapper around request: https://github.com/gitterHQ/request-http-cache. It is based on this: https://github.com/suprememoocow/request-extensible which also could be a good idea in case a different caching library is preferred.
