### ISSUE TITLE
`getUrl` removes template markers

### ISSUE THREAD

**Issue by amannn** [basti1302/traverson#58]
First of all, really great library!

I'm currently encountering an issue when using the `getUrl` function. Apparently the result that is passed to the callback, has all template markers removed.

So e.g. when the final URL should be `http://something.tld/books{?page,size,sort,projection}`, the url that is passed to the callback is `http://something.tld/books`.

For my usecase I'd actually like to have the template markers.

Is there a specific reason for this? Or maybe did I do something wrong?

**Comment by basti1302** [comment]
The URI template processing happens before the URL is returned to the callback. The reason is kind of "that's just the way it works". If you know the proper substitions for the URI template parameters ahead of time you can just use Traverson's [withTemplateParameters](https://github.com/basti1302/traverson/blob/master/user-guide.markdown#uri-templates) method and let Traverson handle the substitution for you.

If you want the full template and resolve it yourself later then I am afraid that there is no way to do this currently. I'm open to suggestions for an API that would allow that.

**Comment by amannn** [comment]
Thanks for the quick response!

Oh I actually missed that `getUrl` also works with `withTemplateParamters`. That actually works for my usecase, so there's no need for a change.

Thanks again!

**Comment by basti1302** [comment]
I added a clarification to the user guide and the API docs for this.
