### ISSUE TITLE
Post authorization

### ISSUE THREAD

**Issue by hellsingblack** [basti1302/traverson#61]
I tried to post with authorization to get a token, seems I can not add Authorization in the header.

```javascript
                const api = Traverson.from('https://my-url-token/oauth/token');
  		const auth = 'Basic ' + btoa('username:password');

  		api.newRequest()
  		   .withRequestOptions({
		        headers: {
		            'Authorization' : auth
		        },
			    qs: { 
			       'grant_type': 'client_credential',
			       'scope': 'api'
			    }
  		   })
  		   .post(null,function(err, response, traversal){

				
  		   })

```

**Comment by basti1302** [comment]
Hi,

thanks for the report. Could you answer some questions to help me understand your problem better? Thanks in advance.

1. Are you using Traverson in the browser or in Node.js?
1. What did you expect to happen? 
1. What happened instead? 
1. What error did you get?

**Comment by hellsingblack** [comment]
1 - I use it with node.js 
2 - like this page https://api-sandbox.slimpay.net/docs/#step-2-retrieve-an-access-token-under-the-api-scope, I would like to receive

equivalent in curl:
curl -u "democreditor01:demosecret01" \
     -d "grant_type=client_credentials&scope=api" \
     https://api-sandbox.slimpay.net/oauth/token

```javascript 
{
  "access_token" : "899a8019-328d-41bb-876a-980f1c768453",
  "token_type" : "bearer",
  "expires_in" : 985,
  "scope" : "api"
}
```

instead I get CORS issue 

Fetch API cannot load https://api-sandbox.slimpay.net/oauth/token?grant_type=client_credentials&scope=api. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by basti1302** [comment]
This sounds more like a CORS issue with your backend service. I still don't understand your setup completely.

One thing I noticed: curl with -d will send the the payload application/x-www-form-urlencoded in the request *body*. You are trying sending to send it as the query string in your corresponding Traverson code snippet, that is, as part of the *URL*. This is not the same. Not sure if this is the root cause of your problem.

Where does http://localhost:4000 come into all of this? Is this the server side that you have implemented yourself? What is https://my-url-token/oauth/token (mentioned in your original issue)? Is this also your localhost backend, using some kind of alias?

If you wrote the backend yourself, maybe you backend just needs to set the correct CORS headers for your use case?

**Comment by basti1302** [comment]
FWIW, I just add a test just to make sure that the 'Authorization' header is sent correctly to the server - it is. See [this commit](https://github.com/basti1302/traverson/commit/2dd462f010e8c4e9988d43fd9c85a75a3f0002c3).

The backend used here is a very basic [Express](http://expressjs.com/) backend, if you are using express, you maybe should have a look at the [cors](https://www.npmjs.com/package/cors) module.

This is the code that I use to deal with CORS:

```
  // enable CORS header
  app.use(cors({
    credentials: true,
    origin: 'http://localhost:' + app.get('port'),
    exposedHeaders: ['Location'],
  }));

  // enable pre-flight for put/patch/delete
  app.options('*', cors());
```

Of course, this is only used for a local test server, your requirements might be different.

Since your error message mentions that the preflight request (the OPTIONS request that is executed automatically before the POST request) is the problem, maybe all you need to do is to enable CORS headers for the OPTIONS method in your backend.

**Comment by hellsingblack** [comment]
In fact the slimpay api I send you above is not mine. In the documentation of slimpay, you can talk to the api with token so, the first step is to POST to https://api-sandbox.slimpay.net

Traverson.from('https://api-sandbox.slimpay.net/oauth/token'); with headers Authorization as specified in the documentation. I use webpack server and my local is localhost:4000.

```javascript 
       const api = Traverson.from('https://api-sandbox.slimpay.net/oauth/token');
        const auth = 'Basic ' + btoa('username:password');

        api.newRequest()
           .withRequestOptions({
                headers: {
                    'Authorization' : auth
                },
                qs: { 
                   'grant_type': 'client_credential',
                   'scope': 'api'
                }
           })
           .post(null,function(err, response, traversal){

                 
           })
```

I expect the post response return a json such as 

```javascript 
{
  "access_token" : "899a8019-328d-41bb-876a-980f1c768453",
  "token_type" : "bearer",
  "expires_in" : 985,
  "scope" : "api"
}
```

and use the access_token. But as you said it may an api issue

**Comment by hellsingblack** [comment]
An example from: https://dev.slimpay.com/hapi/browser#get-orders

# Note: This is not pure HTTP, some of the following
# is based on variables but it can help you with the
# correct Headers and Message body you need to send.

# Step: HTTP Basic Authentication
POST	https://api-sandbox.slimpay.net/oauth/token

Accept: application/hal+json; profile="https://api.slimpay.net/alps/v1"
Authorization: Basic Base64(hbih9vahrbk5a:zjMzjc5HhdOtK#Rpo3dub2YfQQZ6)
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=api

# The response contains a token that we now use as Bearer
# Step: GET the entry point Resource
GET	https://api-sandbox.slimpay.net/

Accept: application/hal+json; profile="https://api.slimpay.net/alps/v1"
Authorization: Bearer token
Content-Type: application/json

# Step: Follow a Link on the last Resource
# URL variables: creditorReference=hbih9vahrbk5a
GET	Follow(https://api.slimpay.net/alps#get-orders)

Accept: application/hal+json; profile="https://api.slimpay.net/alps/v1"
Authorization: Bearer token
Content-Type: application/json

**Comment by basti1302** [comment]
You said "I use it with Node.js". Are you sure? What I mean is - is your Traverson code running in a Node.js process or in a browser. Since you mentions webpack, I very much suspect your code is actually executed by a browser, right?

The following works for me without problems in *Node.js*:

```
'use strict';

const traverson = require('../traverson');
let btoa_ = null;
if (typeof btoa === 'function') {
  btoa_ = btoa
} else {
  btoa_ = require('btoa');
}

const api = traverson.from('https://api-sandbox.slimpay.net/oauth/token');
const auth = 'Basic ' + btoa_('democreditor01:demosecret01');

api
.newRequest()
.withRequestOptions({
  headers: {
    'Authorization' : auth
  },
  qs: {
    'grant_type': 'client_credentials',
    'scope': 'api'
  }
})
.post(null,function(err, response, traversal){
  console.log(err);
  console.log(response.statusCode);
  console.log(response.statusMessage);
  console.log(response.body);
});
```

However, when I browserify this and try it in Chrome, I can reproduce your CORS problem. I'll dig a bit deeper and let you know what I find.

**Comment by hellsingblack** [comment]
Yes in browser, I tried to find something to fix this bug in browser, however not really relevant. May I use bad for this case. Thanks for your answer.

**Comment by basti1302** [comment]
In the browser, I use superagent under the hood for making HTTP requests. This automatically adds a Content-Type header application/json which in turn causes the preflight request. See https://github.com/visionmedia/superagent/issues/501.

Not much I can do about that right now, I'm afraid.

**Comment by basti1302** [comment]
It's funny, but I think the `Authorization` header alone triggers a preflight request and you need it to access the resource, still, slimpay has not enabled CORS there. That would mean you could not use the API via AJAX at all. Maybe I'm missing something here. Might be worth to talk to the folks at @SlimPay about that? Pinging @YoussefBO: could you folks enable CORS headers on OPTION requests to /oauth/token ?

----

I did some more digging because I'm still not sure if this hints at a problem with traverson or not. So the stuff I write here is also meant to document my findings if this should come up again in a different use case.

For what it's worth, the **following code works** if chrome/chromium is started with web-security disabled (like, `google-chrome --disable-web-security --user-data-dir`):

```
api
.newRequest()
.withRequestOptions({
  headers: {
    'Authorization': auth,
    'content-type': 'application/x-www-form-urlencoded',
  },
  qs: {
    'grant_type': 'client_credentials',
    'scope': 'api'
  }

})
.post(null,function(err, response, traversal){
  console.log(err);
  console.log(response.statusCode);
  console.log(response.statusMessage);
  console.log(response.body);
});
```

Of course, this doesn't help much since your users don't do that.

As an aside, also for future reference, in the next version of Traverson, this would also work (again, with web security disabled):

```
  headers: {
    'Authorization': auth,
  },
  form: {
    'grant_type': 'client_credentials',
    'scope': 'api'
  }
```

(there was a small bug in superagent usage regarding to the form parameter.)

**Comment by hellsingblack** [comment]
👍

**Comment by YoussefBO** [comment]
Hi guys,

CORS headers have been enabled on our Sandbox https://api-sandbox.slimpay.net and the production will follow soon https://api.slimpay.net (during next week).

Thanks for the ping ;)

**Comment by basti1302** [comment]
Cool :+1:
