### ISSUE TITLE
`httpStatus` of error in getUrl callback not available in Firefox

### ISSUE THREAD

**Issue by amannn** [basti1302/traverson#71]
I've noticed that the callback of `getUrl` doesn't have `httpStatus` set on the error object in Firefox.

I'm particularly interested into a request that might fail with the status code 401. While I can check for this in browsers like Chrome and Safari, this doesn't work in Firefox.

Do you know what the root of this problem is?

**Comment by basti1302** [comment]
I'm not sure I follow. `getUrl` does not actually execute the HTTP request at all. (Of course, if it is a traversal process with multiple steps, it will execute the intermediate requests, only excluding the last one). See https://github.com/basti1302/traverson/blob/master/api.markdown, docs for getUrl. The idea here is that you can execute the request yourself. So you should never get an 401 error from Traverson because the request has not been executed.

Are you talking about the case where an **intermediate** URL fails with 401?

**Comment by basti1302** [comment]
For what it's worth, I added a test for the case where, during a `getUrl` traversal, an intermediate URL fails with 404 and this works fine in Firefox for me. Could you check again? If you still think that this is a Traverson issue, please feel free to reopen this bug and provide more detail, or better yet, a complete reproducible test case that fails in Firefox for you. Also, knowing the OS and Firefox version might help.

**Comment by amannn** [comment]
Thanks for your response! Maybe it was my apps fault then. I've worked around the problem for now, but if I revisit it in the future and still discover the problem I'll provide a reproducible test case.
