### ISSUE TITLE
Pull Request for LinkHeader support

### ISSUE THREAD

**Issue by iunanua** [basti1302/traverson#84]
We would like to extend traverson to consume an API that returns the links using the LinkHeader specification [1].
 
Our first approach is to create a new LinkHeaderAdapter adapter. This adapter makes use of the "parse-link-header" library [2] to parse the links contained in the header of the HTTP response.
 
Once the LinkHeaderAdapter is registered, we are able to traverse the relation of the links, from an angular client, in the same way as for HAL.

When using HAL, getResource callback is invoked by passing a parsed Resource. This Resource contains a collection of links in `_links` property of the object, as it is defined in HAL specification.
However that is not the case for LinkHeaders, as the collection of links is not contained in the object of the response.

After our analysis we identified that a good approach could be to upgrade findNextStep method in LinkHeaderAdapter so that appart from the URL it could return the collection of links to be stored in the actual step. The remaining decision is how should we pass the collection to the final callback.

One option could be to define a new method in the adapter called `onParsedBody`. Traverson should invoke it after the parser sets the `doc` in the step. In this way, the adapter will be able to include additional properties in the returned `doc`, in our case the collection of links:

```javascipt
function parseBody(t) {
  log.debug('parsing response body');
  if (t.requestOptions && t.requestOptions.jsonReviver) {
      t.step.doc = t.step.response.body;
  } else {
      t.step.doc = t.jsonParser(t.step.response.body);
  }
  if (t.adapter.onParsedBody) {
      t.adapter.onParsedBody(t);
  }
}
```

This design is obviously our initial proposal, we are open to do any change you may think it is interesting in other to properly adapt it to the library.

Would you be interested in letting us make a PR to include this changes inside traverson? :)

[1] https://www.w3.org/wiki/LinkHeader
[2] https://github.com/thlorenz/parse-link-header

**Comment by basti1302** [comment]
I like the idea of supporting the link header very much!

Some things to consider:

1. If I understand your proposal, you would provide LinkHeader as a separate Adapter. Adapters are intended to support different media types, like HAL, Mason, etc - kind of like a plug-in system. (Though I never got around to implement another adapter besides the basic JSON adapter and the HAL adapter). I am not 100% sure if the Link header can be considered a different media type, or if users should be able to use Link headers _in combination_ with another media type? Then implementing it as an Adapter would be the wrong way, instead it would have to be a feature of Traverson's core functionality.
1. Traverson already provides support for the Location header, see https://github.com/basti1302/traverson/blob/master/api.markdown#configuration-methods (look for followLocationHeader(). However, using the location header can be inserted as a single step in the middle of following "normal" links that are contained in the response body. Thus, you can mix normal link traversal and Location header usage freely. Using the Link header the way you suggest it would have a very different API and a different feel from using the Location header. Maybe this is okay, because the two headers are used differently anyway, I'm not sure yet.
1. An implementation detail: `thlorenz/parse-link-header` uses the `url` module from Node. Be aware that Traverson's `package.json` defines a shim for this Node core module to reduce the browserified file size, see [here](https://github.com/basti1302/traverson/blob/master/package.json#L106). Depending on which features of the `url` module parse-link-header needs, this might be an issue.
1. You already identified the findNextStep method of the adapter as a potential place that needs to be changed. If you have a look at [JsonAdapter's findNextStep method](https://github.com/basti1302/traverson/blob/master/lib/json_adapter.js#L23) you can see that it already deals with headers (currently only with the Location header, see above). Could this be used to also support the Link header? I'm really not sure, it is just an open question.

Kind regards

  Bastian

**Comment by iunanua** [comment]
Hi Bastian!

> I like the idea of supporting the link header very much!

Nice!

1. As you say can not be considered as a different media type and the adapters are linked to the media type, but we believe that it will not be used in combination with other adapters. However we have no preference whether if it is an adapter or is supported by the core.

2. Could be done in the same way as for Location but, if possible, we would like that in the expression of the `follow()` we would not have to specify the `type` each time :)

3. Upss, it is a detail that we had not taken into account. We'll have to look at it.

4. Yes, it can be used.  In the case of Link Header, `findNextStep()` must parse the headers to return the next step. 
But in addition to returning the step we want that in the last step, when traverson is asked for a `getResource()`, in the resource comes a property `_links` including the extracted links of the header.

**Comment by anderruiz** [comment]
Hi Bastian!, Is there anything in which we can help you to integrate the PR? or any modification you would like to be done before including it?

Do not hesitate to ask us any change :)

**Comment by basti1302** [comment]
Let's continue the discussion in the PR, not here.

Closing in favor of #85.
