### ISSUE TITLE
How to write integration tests for traverson? 

### ISSUE THREAD

**Issue by pzmudzinski** [basti1302/traverson#89]
I would like to write some integration tests, e.g. making sure:
1. My component does request for a root URL and traverses through provided links,
2. Parses and displays response in a correct manner

I was thinking about writing stub server which will return dummy responses. 
I've tried [pretender lib ](https://github.com/pretenderjs/pretender), like here:
```
const dummyResponseHeaders = {
  'content-type': 'application/json',
};

const createResponse = (responseBody) => {
  const response = [
    200,
    dummyResponseHeaders,
    JSON.stringify(responseBody),
  ];

  return response;
};
const server = new Pretender(function() {
   this.get(rootUrl, () => {
     createResponse(dummyRootResponse);
   });

  this.get(dummyRootResponse._links.myItems.href, () => {
    createResponse(dummyItems);
  });
});
```

But it seems that `traverson` isn't compatible with `Pretender` server (although it's working with regular `fetch`). So..
What can I use for stubbing HTTP responses?

**Comment by travi** [comment]
I have had success doing this with [nock](https://github.com/node-nock/nock)

**Comment by travi** [comment]
looking at pretender more closely, it looks like it is a browser library since it focuses on stubbing the XHR. i only use traverson in node api client, not in the browser, so that is where my nock recommendation comes from. if you are using traverson in the browser, you could also consider sinon's [fake server](http://sinonjs.org/releases/v1.17.7/fake-xhr-and-server/)

**Comment by pzmudzinski** [comment]
Yes, I am using traverson inside React app. `nock` worked out great. Thank you @travi
